### ISSUE TITLE
Final NMIND 

### ISSUE THREAD

**Issue by LuciMoore** [ohspc89/hbcd_motion_postproc#1]
One super simple recommendation from NMIND before final approval! copied from [here](https://github.com/nmind/proceedings/issues/19#issuecomment-2513325010):

"One minor suggested change is related to `infrastructure / silver / no excessive files`. There are a couple of .DS_STORE files, which I believe are macOS specific related to attributes? These can probably be removed, or the checklist can be updated (see below) unless there is a necessity for it."

**Comment by ohspc89** [comment]
@LuciMoore .DS_Store removed!
